// Cross-check the C++ core against Julia reference CSVs (generated by
// cpp/reference/dump_reference.jl). The (θ,φ) configs are read verbatim from the CSVs, so the
// comparison is purely numerical. Usage: test_reference <reference_dir>
#include <cfsonsphere/cfsonsphere.hpp>

#include <complex>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using namespace cfs;

static int g_failures = 0;
static int g_checks = 0;
#define CHECK_NEAR(a, b, tol)                                                          \
    do {                                                                               \
        ++g_checks;                                                                    \
        double _d = std::abs((a) - (b));                                               \
        if (!(_d <= (tol))) {                                                          \
            std::printf("FAIL %s:%d  diff = %.3e > %.3e\n", __FILE__, __LINE__, _d,    \
                        (double)(tol));                                                \
            ++g_failures;                                                              \
        }                                                                              \
    } while (0)

static std::string DIR;
static std::string path(const std::string& f) { return DIR + "/" + f; }

static std::vector<double> read_vec(const std::string& p) {
    std::ifstream f(p);
    std::vector<double> v;
    double x;
    while (f >> x) v.push_back(x);
    return v;
}

static Eigen::MatrixXcd read_cmat(const std::string& p) {
    std::ifstream f(p);
    int rows, cols;
    f >> rows >> cols;
    Eigen::MatrixXcd M(rows, cols);
    for (int idx = 0; idx < rows * cols; ++idx) {
        double re, im;
        f >> re >> im;
        M(idx % rows, idx / rows) = cdouble(re, im);  // column-major
    }
    return M;
}

static cdouble read_scalar(const std::string& p) {
    std::ifstream f(p);
    double re, im;
    f >> re >> im;
    return cdouble(re, im);
}

static double maxdiff(const Eigen::MatrixXcd& A, const Eigen::MatrixXcd& B) {
    return (A - B).cwiseAbs().maxCoeff();
}

static void check_esp() {
    Eigen::MatrixXcd roots_m = read_cmat(path("esp_roots.csv"));
    std::vector<cdouble> roots(roots_m.data(), roots_m.data() + roots_m.size());
    const int nroots = static_cast<int>(roots.size());
    const int b = 8;
    for (int mult : {1, 2, 3}) {
        const int Npart = 13;
        std::vector<double> reg(b);
        for (int i = 1; i <= b; ++i) reg[i - 1] = double(i) / (mult * (Npart - 1) - i + 1);
        std::vector<cdouble> dest(b + 1);
        get_symmetric_polynomials(dest.data(), roots.data(), nroots, b, reg.data(), mult);
        Eigen::MatrixXcd ref = read_cmat(path("esp_mult" + std::to_string(mult) + ".csv"));
        double md = 0;
        for (int d = 0; d <= b; ++d) md = std::max(md, std::abs(dest[d] - ref(d, 0)));
        std::printf("ESP mult=%d  maxdiff=%.3e\n", mult, md);
        CHECK_NEAR(md, 0.0, 1e-12);
    }
}

static void check_projection_coeff() {
    std::ifstream f(path("projection_coeff.csv"));
    std::string line;
    double md = 0;
    while (std::getline(f, line)) {
        if (line.empty()) continue;
        std::istringstream ss(line);
        int two_L, two_Qstar, two_Q1, two_m;
        double val;
        ss >> two_L >> two_Qstar >> two_Q1 >> two_m >> val;
        double cpp = projection_coeff(two_L, two_Qstar, two_Q1, two_m);
        md = std::max(md, std::abs(cpp - val));
    }
    std::printf("projection_coeff  maxdiff=%.3e\n", md);
    CHECK_NEAR(md, 0.0, 1e-12);
}

static void check_proj(const std::string& tag, int N, int n, int p, int jk_type) {
    auto [twoQ, lm] = cf_ground_state_lm(N, n, p);
    const int Nsys = static_cast<int>(lm.size());
    auto tv = read_vec(path("theta_" + tag + ".csv"));
    auto pv = read_vec(path("phi_" + tag + ".csv"));
    Eigen::VectorXd th = Eigen::Map<Eigen::VectorXd>(tv.data(), Nsys);
    Eigen::VectorXd ph = Eigen::Map<Eigen::VectorXd>(pv.data(), Nsys);
    PsiProj psi(twoQ, p, Nsys, lm, jk_type);
    psi.update(th, ph);
    double md = maxdiff(psi.slater_det, read_cmat(path("slater_" + tag + ".csv")));
    double jd = std::abs(psi.jastrow_factor_log - read_scalar(path("jastrow_" + tag + ".csv")));
    std::printf("%s  slater maxdiff=%.3e  jastrow diff=%.3e\n", tag.c_str(), md, jd);
    CHECK_NEAR(md, 0.0, 1e-12);
    CHECK_NEAR(jd, 0.0, 1e-10);
}

static void check_unproj(const std::string& tag, int N, int n, int p) {
    auto [twoQ, lm] = cf_ground_state_lm(N, n, p);
    const int Nsys = static_cast<int>(lm.size());
    auto tv = read_vec(path("theta_" + tag + ".csv"));
    auto pv = read_vec(path("phi_" + tag + ".csv"));
    Eigen::VectorXd th = Eigen::Map<Eigen::VectorXd>(tv.data(), Nsys);
    Eigen::VectorXd ph = Eigen::Map<Eigen::VectorXd>(pv.data(), Nsys);
    PsiUnproj psi(twoQ, p, Nsys, lm);
    psi.update(th, ph);
    double md = maxdiff(psi.slater_det, read_cmat(path("slater_" + tag + ".csv")));
    double jd = std::abs(psi.jastrow_factor_log - read_scalar(path("jastrow_" + tag + ".csv")));
    std::printf("%s  slater maxdiff=%.3e  jastrow diff=%.3e\n", tag.c_str(), md, jd);
    CHECK_NEAR(md, 0.0, 1e-12);
    CHECK_NEAR(jd, 0.0, 1e-10);
}

int main(int argc, char** argv) {
    DIR = argc > 1 ? argv[1] : "reference";
    {
        std::ifstream probe(path("slater_proj1.csv"));
        if (!probe.good()) {
            std::printf("reference CSVs not found in '%s' (run cpp/reference/dump_reference.jl); skipping\n",
                        DIR.c_str());
            return 0;
        }
    }
    check_esp();
    check_projection_coeff();
    check_proj("proj1", 10, 2, 1, 1);
    check_proj("proj2", 10, 2, 2, 2);
    check_unproj("unproj", 9, 3, 1);
    std::printf("\n%d checks, %d failures\n", g_checks, g_failures);
    return g_failures == 0 ? 0 : 1;
}
